[build]
  # Directory to change to before starting a build.
  # This is where we will look for package.json/.nvmrc/etc.
  base = "project/"

  publish = "project/build-output/"

  command = "echo 'default context'"

  functions = "project/functions/"

[context.production]
  publish = "project/output/"
  command = "make publish"
  environment = { ACCESS_TOKEN = "super secret", NODE_VERSION = "8.0.1" }

[context.deploy-preview]
  publish = "project/dist/"

[context.deploy-preview.environment]
  ACCESS_TOKEN = "not so secret"

[context.branch-deploy]
  command = "echo branch"
[context.branch-deploy.environment]
  NODE_ENV = "development"

[context.staging] # 'staging' is a branch name
  command = "echo 'staging'"
  base = "staging"

[context."feat/branch"]
  command = "echo 'special branch'"
  base = "branch"



[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
