[build]
  base = "project/"

  publish = "project/build-output/"

  command = "echo 'default context'"

  functions = "project/functions/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
